os: linux
language: java

stages:
  - test

before_script:
  - ./gradlew install

jobs:
  include:
    - stage: test
      jdk: oraclejdk9
      name: KotlinConsumer
      script:
        - cd KotlinConsumer
        - ./gradlew test
    - stage: test
      jdk: oraclejdk11
      name: SpringConsumer
      env:
        - updateSnapshots=1
      script:
        - cd SpringConsumer
        - ./gradlew test
    - stage: test
      jdk: oraclejdk8
      name: AndroidConsumer
      env:
        - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.0-rc02
          - android-28
      script:
        - cd AndroidConsumer
        - ./gradlew test
