language: android
sudo: required
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)
    - SH=bash

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0-rc02
    - build-tools-27.0.3
    - android-27
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew ktlint test install
  - cd ../SpringConsumer
  - updateSnapshots=1 ./gradlew test --debug
  - exit 0
  - cd KotlinConsumer
  - ./gradlew test
  - cd ../AndroidConsumer
  - ./gradlew test
