language: android
os: linux
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk8
  - oraclejdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0-rc02
    - android-28

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: Build Plugin
      jdk: oraclejdk8
      script:
        - ./gradlew install
    - stage: test
      jdk: oraclejdk8
      name: KotlinConsumer
      script:
        - cd KotlinConsumer
        - ./gradlew test
    - stage: test
      jdk: oraclejdk11
      name: SpringConsumer
      env:
        - updateSnapshots=1
      script:
        - cd SpringConsumer
        - ./gradlew test
    - stage: test
      jdk: oraclejdk8
      name: AndroidConsumer
      script:
        - cd AndroidConsumer
        - ./gradlew test
